# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "009b50554c5e2d1d08ab29ccdabb133b"
name = "Sticky Cart - V2"
application_url = "https://sticky-cart-v2.onrender.com"
embedded = true

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2026-01"

[[webhooks.subscriptions]]
topics = ["app/uninstalled"]
uri = "/api/webhooks"

[[webhooks.subscriptions]]
topics = ["customers/data_request"]
uri = "/api/webhooks"

[[webhooks.subscriptions]]
topics = ["customers/redact"]
uri = "/api/webhooks"

[[webhooks.subscriptions]]
topics = ["shop/redact"]
uri = "/api/webhooks"

[access_scopes]
scopes = "write_themes"

[auth]
redirect_urls = [
  "https://sticky-cart-v2.onrender.com/auth/callback",
  "https://sticky-cart-v2.onrender.com/auth/shopify/callback",
  "https://sticky-cart-v2.onrender.com/api/auth/callback"
]
