# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "009b50554c5e2d1d08ab29ccdabb133b"
name = "Sticky Cart - V2"
application_url = "https://sticky-cart-v2.onrender.com"
embedded = true

[webhooks]
api_version = "2026-01"

[[webhooks.subscriptions]]
topics = [ "app/uninstalled", "customers/data_request", "customers/redact", "shop/redact" ]
uri = "/api/webhooks"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_themes"
optional_scopes = [ ]
use_legacy_install_flow = false

[auth]
redirect_urls = [ "https://sticky-cart-v2.onrender.com/auth/callback" ]
